Update to pitivi 2020.09.0
flathub/org.pitivi.Pitivi pull request #17
Opened 2020-10-05 15:21 UTC by thiblahute

2020-10-05 18:34 UTC, aleb requested changes

2020-10-05 18:34 UTC, aleb commented on org.pitivi.Pitivi.json
> +        "python3-pylint.json",
These 4 are not needed

2020-10-06 07:47 UTC, A6GibKm commented
The new runtime should come with lame 3.100, you might remove line 136
```patch
-        "shared-modules/lame/lame-3.99.5.json",
```

2020-10-06 07:51 UTC, A6GibKm commented
@aleb  could you please consider giving support to the 3.38 GNOME runtime for a future 20.09.1 release?

2020-10-06 07:57 UTC, A6GibKm commented on org.pitivi.Pitivi.json
>                      "url" : "git://anongit.freedesktop.org/gstreamer/gstreamer",
Isn't https://gitlab.freedesktop.org/gstreamer.git the correct url?

2020-10-06 11:41 UTC, thiblahute commented
> @thiblahute @aleb could you please consider giving support to the 3.38 GNOME runtime for a future 20.09.1 release?

We might but we should have the change happen upstream and tested before we make the change in flathub.

2020-10-06 19:49 UTC, thiblahute commented
> The new runtime should come with lame 3.100, you might remove line 136
> 
> ```diff
> -        "shared-modules/lame/lame-3.99.5.json",
> ```
> 
> Edit: This is the case for GNOME 3.38. I don't know about 3.36. In any case have a look at https://gitlab.gnome.org/GNOME/pitivi/-/blob/2020.09.0/build/flatpak/org.pitivi.Pitivi.json#L135.

I did check and it is in 3.36 too.

2020-10-06 20:03 UTC, hfiguiere commented
When I launch this build, I get:

```
Failed to initialize modules
Traceback (most recent call last):
  File "/app/bin/pitivi", line 152, in <module>
    _initialize_modules()
  File "/app/bin/pitivi", line 129, in _initialize_modules
    initialize_modules()
  File "/app/lib/pitivi/python/pitivi/check.py", line 399, in initialize_modules
    if validate.init() and "--inspect-action-type" in sys.argv:
  File "/app/lib/pitivi/python/pitivi/utils/validate.py", line 558, in init
    Gst.info("Adding pitivi::wrong-window-creation")
  File "/usr/lib/python3.7/site-packages/gi/module.py", line 132, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gst' object has no attribute 'info'
```

It fails.

2020-10-06 20:09 UTC, A6GibKm commented
I will add
```
** (gst-plugin-scanner:5): CRITICAL **: 22:09:23.541: Couldn't g_module_open libpython. Reason: /usr/lib/x86_64-linux-gnu/libpython3.7m.so: cannot open shared object file: No such file or directory
```
To the issue above.

2020-10-06 20:38 UTC, thiblahute commented
Thanks for testing, updated now, let's see how it goes :-)

2020-10-06 21:58 UTC, A6GibKm commented
Now
```
ERROR - The following hard dependencies are unmet:
==================================================
- Peas not found on the system
```
It might be the case that it the dependency is missing in the meson file too? For convenience: https://gitlab.gnome.org/GNOME/pitivi/-/blob/master/build/flatpak/org.pitivi.Pitivi.json#L529.

2020-10-06 22:09 UTC, thiblahute commented
Yeah, that is the reason, although it is interesting that libpeas is not in the GNOME Sdk.

2020-10-06 23:58 UTC, thiblahute commented
Look all good to me, @aleb, do you want to give it a try and merge?

2020-10-08 00:55 UTC, thiblahute commented
OK, getting it in.

2020-10-08 00:55 UTC, merged