Update to GNOME 40
flathub/org.pitivi.Pitivi pull request #24
Opened 2021-03-25 00:21 UTC by hfiguiere

2021-04-10 00:41 UTC, hfiguiere commented
@aleb @thiblahute can I merge this ?

2021-04-14 15:03 UTC, aleb commented
I don't have time to test. I'll get back after we update the dev env.

2021-05-31 12:21 UTC, thiblahute commented
Our [developement environment](https://developer.pitivi.org/HACKING.html?gi-language=undefined) in Pitivi is based on Flatpak and we should always have the flatpak manifest from there in sync with this one, starting by updating the one in the pitivi repo and then merging updating this on.

2021-11-13 22:42 UTC, hfiguiere commented
The thing is that now 3.38 is deprecated and you never took the patch.

2021-11-14 23:35 UTC, thiblahute commented
@aleb this should be good to go now right?

2021-11-15 10:26 UTC, aleb commented
Not sure if there are issues with 40. The dev env is on 41 now.

2021-11-15 13:28 UTC, aleb commented
Then we need to change the pygobject path in the json manifest.

2021-11-15 14:01 UTC, hfiguiere commented
you already need to change the pre-built wheels because the python version got upgraded.

2022-02-17 01:16 UTC, hfiguiere commented
Reworked it to update to GNOME 41:

- updated python package for 3.9 compatibility
- updated gstreamer to latest for the branch
- patched appdata for missing screenshot

2022-02-17 02:51 UTC, hfiguiere commented
evidence that:
1. python package should be build from source
2. that I only built on aarch64

2022-03-14 23:46 UTC, hfiguiere commented
bot, build

2022-03-17 03:02 UTC, hfiguiere commented
This works here on x86_64

2022-03-23 02:33 UTC, hfiguiere commented
Now with GNOME 42.

2022-03-23 03:08 UTC, hfiguiere commented
build fail because libcanberra.

2022-03-23 23:07 UTC, hfiguiere commented
this update uses libcanberra from shared-modules

2022-03-23 23:08 UTC, hfiguiere commented
bot, build

2022-03-24 01:17 UTC, hfiguiere commented
bot, build

2022-03-26 20:03 UTC, hfiguiere commented
that build failure is back...

2022-03-26 22:39 UTC, A6GibKm commented
I think that gst-plugging-base is in the runtime. See the error I am getting in my PR, the metainfo also needs patching since the screenshots urls do not exist anymore.

2022-03-31 17:43 UTC, hfiguiere commented
> I think that gst-plugging-base is in the runtime. See the error I am getting in my PR, the metainfo also needs patching since the screenshots urls do not exist anymore.

Updated gstreamer and patched the appdata.

2022-04-01 04:21 UTC, hfiguiere commented
This build is broken because of gst-python: python path did change. Will update.

2022-04-02 19:41 UTC, aleb commented
Can we just copy `shared-modules/libcanberra/libcanberra.json` over instead of using the shared-modules submodule? I'd rather never have to deal with git submodules again.

2022-04-02 19:41 UTC, aleb requested changes

2022-04-02 19:41 UTC, aleb commented on pitivi-appdata.patch
> ++      <image>http://www.pitivi.org/i/screenshots/2020.05.png</image>
https

2022-04-02 20:50 UTC, hfiguiere commented
> Can we just copy `shared-modules/libcanberra/libcanberra.json` over instead of using the shared-modules submodule? I'd rather never have to deal with git submodules again.

And then it end up back to the same situation where things break and don't get updated. `shared-modules` are maintained properly and save a lot of time.

2022-04-02 20:56 UTC, A6GibKm commented
> Can we just copy `shared-modules/libcanberra/libcanberra.json` over instead of using the shared-modules submodule? I'd rather never have to deal with git submodules again.

The point of using it is precisely so that modules are well maintained and not broken, note that this is precisely what happened here where it needed both a patch and a newer url.

2022-04-02 21:11 UTC, aleb commented
The submodule also has to be updated, it does not update by itself, no? 

It's great that the shared-modules is well maintained, I'm all for copying what we need from there.

Am I missing anything?

Anyway, I don't even have merge rights in this repo, so don't mind me

2022-04-02 21:14 UTC, hfiguiere commented
> The submodule also has to be updated, it does not update by itself, no?

Nothing updates by itself, but this is the path of least resistance.

> Anyway, I don't even have merge rights in this repo, so don't mind me. You seem to know what you are doing. 👍

Ok I'll merge then.

2022-04-02 21:19 UTC, hfiguiere commented on pitivi-appdata.patch
> ++      <image>http://www.pitivi.org/i/screenshots/2020.05.png</image>
done

2022-04-02 21:20 UTC, hfiguiere commented
Also added fallback-x11 as per #29

2022-04-03 03:10 UTC, merged